// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTC-3QsqPinykHiKultaB9lTO69dIDfyc',
    appId: '1:774916044153:web:641e7b5943b3d0aa55aba8',
    messagingSenderId: '774916044153',
    projectId: 'expecify-flutter',
    authDomain: 'expecify-flutter.firebaseapp.com',
    storageBucket: 'expecify-flutter.appspot.com',
    measurementId: 'G-SMGQ6LJVYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnj1bfz2mlu7GbPpZFarADZ_g4kR-1JDo',
    appId: '1:774916044153:android:e0490aebc54c7dc955aba8',
    messagingSenderId: '774916044153',
    projectId: 'expecify-flutter',
    storageBucket: 'expecify-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1dA2Za25a_lKPcsuyQSUP_haUkHYkxI',
    appId: '1:774916044153:ios:bc7293ba108509bb55aba8',
    messagingSenderId: '774916044153',
    projectId: 'expecify-flutter',
    storageBucket: 'expecify-flutter.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc1dA2Za25a_lKPcsuyQSUP_haUkHYkxI',
    appId: '1:774916044153:ios:bc7293ba108509bb55aba8',
    messagingSenderId: '774916044153',
    projectId: 'expecify-flutter',
    storageBucket: 'expecify-flutter.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTC-3QsqPinykHiKultaB9lTO69dIDfyc',
    appId: '1:774916044153:web:6455a2af3f64491555aba8',
    messagingSenderId: '774916044153',
    projectId: 'expecify-flutter',
    authDomain: 'expecify-flutter.firebaseapp.com',
    storageBucket: 'expecify-flutter.appspot.com',
    measurementId: 'G-FYHPMMLDFV',
  );
}
